image:
  file: .gitpod.Dockerfile
ports:
  - port: 4226
    onOpen: ignore
tasks:
  - name: Build
    env:
      SWIFT_SOURCE_ROOT: /workspace/swift
    before: sccache --start-server
    init: >
      utils/build-script --skip-build-benchmarks \
       --skip-ios --skip-watchos --skip-tvos --swift-darwin-supported-archs "x86_64" \
       --cmake-c-launcher="$(which sccache)" --cmake-cxx-launcher="$(which sccache)" \
       --release-debuginfo --test
